# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TreeCrownWatershed
                                 A QGIS plugin
 Wtyczka segmentująca korony drzew metodą watershed z plików LAS/LAZ
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-08
        copyright            : (C) 2025 by Wojtek Garycki
        email                : gw53905@zut.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TreeCrownWatershed class from file TreeCrownWatershed.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tree_crown_watershed import TreeCrownWatershed
    return TreeCrownWatershed(iface)
